kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: vue-app
  labels:
    app: vue-app
spec:
  to:
    kind: Service
    name: vue-app
  port:
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vue-app
  labels:
    app: vue-app
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: vue-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
  labels:
    app: vue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
        - name: app
          image: image-registry.openshift-image-registry.svc:5000/vue-app/vue-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
